export const modalDetails = {
    successModalContainer: "modal success--modal",
    errorModalContainer: "modal error--modal",
    errorModalImg: "https://i.ibb.co/K2K8fDd/error.png",
    successModalImg: "https://i.ibb.co/2511HCS/success.png",
    errorModalButtonClass: "okay--button error__button",
    successModalButtonClass: "okay--button success__ok",
    errorButtonText: "Go home",
    successButtonText: "Login",
    errorButtonNavigationLink: "/signup",
    successButtonNavigationLink: "/login",
    successModalH4Text: "Successful",
    errorModalH4Text: "Error",
    htmlBodyToInsertTheModalIn: document.querySelector("body"),
};
